version: '3'
services:
  # Сервис для MongoDB
  mongo:
    image: mongo
    container_name: mongo
    ports:
      - "27017:27017"
    volumes:
      - mongo-data:/data/db
    deploy:
      restart_policy:
        condition: on-failure

  # Сервис для Backend (Node.js и Express.js)
  backend:
    build: ./backend
    container_name: backend
    ports:
      - "4000:4000"
    depends_on:
      - mongo
    environment:
      MONGO_URI: mongodb://mongo:27017/tripbox
      REACT_APP_FRONTEND_URL: http://localhost:3000
    volumes:
      - ./backend:/backend

    deploy:
      restart_policy:
        condition: on-failure


  # Сервис для Frontend (React)
  frontend:
    build: ./travels
    container_name: frontend
    ports:
      - "3000:3000"
    depends_on:
      - backend
    volumes:
      - ./travels:/frontend
    environment:
      REACT_APP_BACKEND_URL: http://localhost:4000

    deploy:
      restart_policy:
        condition: on-failure


volumes:
  mongo-data: